 - name: install epel repo
   yum:
     name: "{{ epel_repo_url }}"
     state: present
   tags:
     - epel

 - name: import epel gpg key
   rpm_key:
     key: "{{ epel_repo_gpg_key_path }}"
     state: present
   tags:
     - epel